infrastructure:
  network:
  - default

services:
  web:
    image: daocloud.io/hyper2stack/web:1.2
    ports:
    - 8000/tcp
    config_file:
      path: /tmp/web.json
      mode: 644
      content: |
        {
          "mysql_address": "{{with .Singleton "mysql"}}{{.Address}}{{end}}",
          "mysql_port": "{{with .Singleton "mysql"}}{{.Port}}{{end}}",
          "mysql_user": "root",
          "mysql_password": "{{.Runtime.Env "MysqlRootPassword"}}",
          "mysql_db": "{{.Runtime.Env "MysqlDatabaseName"}}"
        }
    depends_on:
    - mysql
    networks:
    - default

  mysql:
    image: daocloud.io/mysql:5.5
    singleton: true
    ports:
    - 3306
    environment:
    - MYSQL_ROOT_PASSWORD={{.Runtime.Env "MysqlRootPassword"}}
    - MYSQL_DATABASE={{.Runtime.Env "MysqlDatabaseName"}}
    networks:
    - default

runtime:
  env:
  - MysqlRootPassword=password
  - MysqlDatabaseName=test
  global_policy:
    restart: always
    port_mapping: fixed
  service_policy:
    web:
      instance_num: 1
