#!/bin/bash

start_service() {
  echo "init mysql..."
  sudo docker inspect moonlegend_db > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    sudo docker run -d --name moonlegend_db -p ${MYSQL_PORT}:3306 -e MYSQL_ROOT_PASSWORD=root daocloud.io/mysql:5.5 > /dev/null
    for x in `seq 1 5`
    do
      sleep 3
      sudo docker exec moonlegend_db mysql -h${IP} -P${MYSQL_PORT} -uroot -proot -e "create database if not exists moonlegend default character set utf8 collate utf8_general_ci;" > /dev/null 2>&1
      [ $? -eq 0 ] && break
      [ $x -eq 5 ] && echo "error: fail to create mysql instance" && exit 1
    done
  else
    echo "init mysql skipped"
  fi

  echo "init moonlegend server..."
  sed -e "s/127\.0\.0\.1:3306/${IP}:${MYSQL_PORT}/g" ${ROOT_DIR}/config/moonlegend.json > /tmp/moonlegend.json
  ${ROOT_DIR}/bin/moonlegend -conf /tmp/moonlegend.json &

  echo "done."
  echo ""
  echo "====== Test ======"
  echo "curl localhost:8080/api/v1/ping"
  echo ""
  echo "====== Runtime Info ======"
  echo "moonlegend config: /tmp/moonlegend.json"
  echo "moonlegend log:    /tmp/moonlegend.log"
  echo "moonlegend mysql:  root:root@tcp(${IP}:${MYSQL_PORT})/moonlegend"
}

stop_service() {
  ps -ef | grep "moonlegend " | grep -v grep | awk '{print $2}' | xargs kill -9
}

remove_service() {
  stop_service
  sudo docker rm -vf moonlegend_db > /dev/null 2>&1
}

#
# main
#

ROOT_DIR=$(readlink -f $(dirname $0))
IP=$(ip route get 8.8.8.8 | head -1 | awk '{print $7}')
MYSQL_PORT=13306

case "${1:-''}" in
  'start')
    start_service
  ;;

  'stop')
    stop_service
  ;;

  'restart')
    stop_service
    start_service
  ;;

  'redeploy')
    remove_service
    start_service
  ;;

  'remove')
    remove_service
  ;;

  *)
    echo "Usage: $0 start|stop|restart|redeploy|remove"
    exit 1
  ;;
esac
